### ISSUE TITLE
Use requirements.txt for installing dependencies

### ISSUE THREAD

**Issue by rlenferink** [ThalesGroup/shapkit#3]
Why not use a `requirements.txt` file for installing dependencies using pip? This lowers the barrier for new contributors.

I am talking about the following list in the README:
```text
numpy (>= 1.17.2)
pandas (>= 0.25.3)
matplotlib (>= 2.2.3)
seaborn (>= 0.9.0)
tqdm [optional] (>= 4.26.0)
```

It is fairly easy to translate this into a `requirements.txt` file:
```
numpy>=1.17.2
pandas>=0.25.3
matplotlib>=2.2.3
seaborn>=0.9.0
tqdm>=4.26.0
```

/cc @ThalesGroup/shapkit-maintainers

**Comment by sgrah-oss** [comment]
You are right ! It is done now

**Comment by rlenferink** [comment]
Wow, good response time !
